# Autogenerated by devscripts/update-version.py

__version__ = '2023.09.06.210111'

RELEASE_GIT_HEAD = 'f426122ceb8387459146812256709c139c959285'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
