# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.03.224610'

RELEASE_GIT_HEAD = 'a058d114179959a8e9cef774d1ffefe89d1b1794'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'DnL888/yt-dlp_sinusbot'

ORIGIN = 'DnL888/yt-dlp_sinusbot'

_pkg_version = '2024.10.03.224610'
