# Autogenerated by devscripts/update-version.py

__version__ = '2023.09.06.195725'

RELEASE_GIT_HEAD = 'f7c8ea99d39798dabde9f8f79132fbab85e12375'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
